paper_len: 10.0
abs_lead_step: 10
# Lead groupings used when plotting with four columns
# (original 4x3 layout)
format_4_by_3: [["I", "II", "III"], ["aVR", "aVL", "aVF", "AVR", "AVL", "AVF"], ["V1", "V2", "V3"], ["V4", "V5", "V6"]]
# Default lead order when plotting 12‑lead ECGs
# Arranged for two columns with six rows
leadNames_12: ["I", 'V1', 'II', 'V2', 'III', 'V3', 'aVR', 'V4', 'aVL', 'V5', 'aVF', 'V6']
tickLength: 8 
tickSize_step: 0.002 
